// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0
//     componentize-go:union

package wasi_cli_0_3_0_types

import ()

const (
	// Input/output error
	ErrorCodeIo uint8 = 0
	// Invalid or incomplete multibyte or wide character
	ErrorCodeIllegalByteSequence uint8 = 1
	// Broken pipe
	ErrorCodePipe uint8 = 2
)

type ErrorCode = uint8
